import { IUtilizador } from '../../shared/i-utilizador';

const DataDummyObjeto: IUtilizador = {
  id: 100,
  email: 'Tony@gmail.com',
  idade: 42,
  activo: true,
  dataRegistro: new Date(),
  departamento: 'comercial de vendas',
  salario: 1000,
};
//export const DataDummy: IUtilizador = [{...DataDummy2}];
export const DataDummy: IUtilizador[] = [
    DataDummyObjeto,
  {
    id: 101,
    email: 'ana@gmail.com',
    idade: 42,
    activo: true,
    dataRegistro: new Date("2023-01-05"),
    departamento: 'dep informatico',
    salario: 1000,
  },
  {
    id: 102,
    email: 'leo@gmail.com',
    idade: 20,
    activo: true,
    dataRegistro: new Date("2025-01-01"),
    departamento: 'dep informatico',
    salario: 1000,
  },
  {
    id: 103,
    email: 'Cidalia@gmail.com',
    idade: 25,
    activo: true,
    dataRegistro: new Date("2024-12-01"),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 104,
    email: 'Asdrubal@gmail.com',
    idade: 55,
    activo: true,
    dataRegistro: new Date("2010-04-10"),
    departamento: 'Chefe de Departamento',
    salario: 2584,
  },
  {
    id: 105,
    email: 'Carlos@gmail.com',
    idade: 49,
    activo: true,
    dataRegistro: new Date("2018-09-23"),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 106,
    email: 'Raquel@gmail.com',
    idade: 28,
    activo: true,
    dataRegistro: new Date("2025-02-05"),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 107,
    email: 'Jose@gmail.com',
    idade: 35,
    activo: true,
    dataRegistro: new Date("2021-01-05"),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 108,
    email: 'Maria@gmail.com',
    idade: 42,
    activo: true,
    dataRegistro: new Date("2000-06-04"),
    departamento: 'comercial de vendas',
    salario: 1000,
  },
  {
    id: 109,
    email: 'Antonio@gmail.com',
    idade: 48,
    activo: true,
    dataRegistro: new Date("2020-01-05"),
    departamento: 'Chefe de Vendas',
    salario: 2000,
  },
  {
    id: 110,
    email: 'Toy@gmail.com',
    idade: 33,
    activo: true,
    dataRegistro: new Date("2022-05-08"),
    departamento: 'TI',
    salario: 1800,
  },
];
